services:
  postgres:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: image_archive_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - image-archive-backend-postgres-data:/var/lib/postgresql/data

volumes:
  image-archive-backend-postgres-data:
